### ISSUE TITLE
Server Crash [Ticking Block Entity]

### ISSUE THREAD

**Issue by Lvl276KBD** [fabric-community/MCDrama#75]
This came out of nowhere, just went to restart my server and now it won't load up. Is there a way to fix this?

---- Minecraft Crash Report ----
// Why did you do that?

Time: 4/20/22, 3:00 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Amount may not be negative, but it is: -720896
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at me.steven.indrev.IREnergyStorage$SideStorage.extract(IREnergyStorage.java:98)
	at team.reborn.energy.api.EnergyStorageUtil.move(EnergyStorageUtil.java:42)
	at me.steven.indrev.utils.MachineinteractionsKt.transferEnergy(machineinteractions.kt:133)
	at me.steven.indrev.blockentities.MachineBlockEntity.tick(MachineBlockEntity.kt:108)
	at me.steven.indrev.blocks.machine.MachineBlock.getTicker$lambda-1(MachineBlock.kt:70)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notNegative(StoragePreconditions.java:50)
	at me.steven.indrev.IREnergyStorage$SideStorage.extract(IREnergyStorage.java:98)
	at team.reborn.energy.api.EnergyStorageUtil.move(EnergyStorageUtil.java:42)
	at me.steven.indrev.utils.MachineinteractionsKt.transferEnergy(machineinteractions.kt:133)
	at me.steven.indrev.blockentities.MachineBlockEntity.tick(MachineBlockEntity.kt:108)
	at me.steven.indrev.blocks.machine.MachineBlock.getTicker$lambda-1(MachineBlock.kt:70)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)

-- Block entity being ticked --
Details:
	Name: indrev:lazuli_flux_container_mk1 // me.steven.indrev.blockentities.storage.LazuliFluxContainerBlockEntity
	Block: Block{indrev:lazuli_flux_container_mk1}[facing=south]
	Block location: World: (-3449,24,-4421), Section: (at 7,8,11 in -216,1,-277; chunk contains blocks -3456,-64,-4432 to -3441,319,-4417), Region: (-7,-9; contains chunks -224,-288 to -193,-257, blocks -3584,-64,-4608 to -3073,319,-4097)
	Block: Block{indrev:lazuli_flux_container_mk1}[facing=south]
	Block location: World: (-3449,24,-4421), Section: (at 7,8,11 in -216,1,-277; chunk contains blocks -3456,-64,-4432 to -3441,319,-4417), Region: (-7,-9; contains chunks -224,-288 to -193,-257, blocks -3584,-64,-4608 to -3073,319,-4097)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713)
	at net.minecraft.class_1937.method_18471(class_1937.java:477)
	at net.minecraft.class_3218.method_18765(class_3218.java:365)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 3425
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,76,0), Section: (at 0,12,0 in 1,4,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 4383982 game time, 1282632 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 3058 (now: true), thunder time: 7094 (now: true)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.class_3176.method_3813(class_3176.java:324)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by dandin87** [comment]
It was fixed in the 1.18.2 version and I backported the fix to the version in the pack. Remove the old IndRev file and use this one. Clients do not need to change anything.
https://cdn.discordapp.com/attachments/876545212900585533/963917743655108648/indrev-1.13.8-BETA-NegEnergyFix.jar

**Comment by Lvl276KBD** [comment]
Thank you so much!

**Comment by sylv256** [comment]
what is this doing here lmfao
